### ISSUE TITLE
Please wear safety glasses

### ISSUE THREAD

**Issue by sajeshcherian** [kevquirk/100daystooffload.com-website#1]
# WATCH OUT!

There's an angle bracket on the loose! Calling all personnel to capture the rogue angle bracket currently in the Guidelines section before somebody gets poked or worse... the [HTML Police](https://validator.w3.org/) arrives on the scene.

![2021-01-17_01-07-21](https://user-images.githubusercontent.com/19327775/104833814-2faef800-5861-11eb-82ea-df3a14d41444.png)

**Comment by kevquirk** [comment]
Haha best issue comment ever. Thanks for letting me know! Fixed.
